# Generated by Django 5.0.7 on 2024-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_phones_price_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='price',
        ),
    ]
