# Generated by Django 5.0.7 on 2024-11-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='item',
        ),
    ]
