# Generated by Django 5.0.7 on 2024-12-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_orders_payment_id_orders_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
