# Generated by Django 5.0.7 on 2024-12-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_address_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
