# Generated by Django 5.0.7 on 2025-01-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Shipped', max_length=20),
        ),
    ]
